### ISSUE TITLE
Modify

### ISSUE THREAD

**Issue by xun666** [manishnagaraj/DOTIE#2]
Quickloading.py -- Line 42 -- `data_path_short = 'datasets/DOTIE_Encoding/QuickLoads_mvsec.hdf5'`
do not match 
Line 35 -- `hf = h5py.File('datasets/QuickLoads_mvsec.hdf5', 'w')`.
Line 42 should be  `data_path_short = 'datasets/QuickLoads_mvsec.hdf5'`.

**Comment by wwgjob** [comment]
Hello, I would like to ask if you will encounter the problem of insufficient memory when loading data. My memory is 64 GB is that enough?

**Comment by manishnagaraj** [comment]
Hi, MVSEC dataset is quite large, you could try loading and encoding a smaller section. I.e., access a subset of `d_set['davis']['left']['events']` in MVSEC_encoding.py

**Comment by manishnagaraj** [comment]
Hi, MVSEC dataset is quite large, you could try loading and encoding a smaller section. I.e., access a subset of `d_set['davis']['left']['events']` in MVSEC_encoding.py
