### ISSUE TITLE
frame_rate setting.

### ISSUE THREAD

**Issue by wwgjob** [manishnagaraj/DOTIE#3]
I'm curious about the reason why you set the rate parameter of MVSEC_encoding.py to 500 when you adjusted it.
Because I am looking at the mvsec dataset using DAVIS camera fps of 50, I want to find out its correlation

**Comment by manishnagaraj** [comment]
The frame rate is directly connected to how sensitive you would want your spiking architecture to be. 
Frame rates that are high -- feed in a smaller number of events to the architecture
Frame rates that are lower (e.g., 50) -- accumulate events and feed a frame with more number of events

Depending on your application, you may need to increase your encoded frame rate. 
If you want the spiking architecture to be more sensitive and distinguish more detailed environments, use higher frame rates.
